CREATE TABLE STUDYROOM(
	NUM VARCHAR(10) PRIMARY KEY,
	STATE TINYINT NOT NULL,
	START_TIME TIMESTAMP,
	END_TIME TIMESTAMP,
	ID VARCHAR(20)
)

---------------------------------------------------------------------
--CREATE TABLE STUDYROOM(
--	NUM VARCHAR PRIMARY KEY,	--좌석번호(1~128)
--	STATE TINYINT NOT NULL,		--자리의 상태 0(비어있음) / 1(남성) / 2(여성)
--	START_TIME TIMESTAMP,		--시작시간
--	END_TIME TIMESTAMP,			--종료시간(시작시간+4시간)
--	ID VARCHAR(20)				--좌석아이디
--)
--
--열람실
--a01~a62는 A열람실 / b01~b42는 B열람실 / c01~c24는 C열람실
---------------------------------------------------------------------

SELECT * FROM STUDYROOM
DROP TABLE STUDYROOM

INSERT INTO STUDYROOM(NUM, STATE) VALUES('a01', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a02', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a03', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a04', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a05', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a06', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a07', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a08', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a09', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a10', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a11', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a12', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a13', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a14', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a15', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a16', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a17', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a18', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a19', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a20', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a21', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a22', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a23', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a24', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a25', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a26', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a27', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a28', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a29', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a30', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a31', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a32', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a33', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a34', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a35', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a36', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a37', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a38', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a39', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a40', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a41', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a42', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a43', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a44', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a45', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a46', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a47', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a48', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a49', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a50', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a51', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a52', 0)
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a01', 0)

