CREATE TABLE STUDYROOM(
	NUM VARCHAR(10) PRIMARY KEY,
	STATE TINYINT NOT NULL,
	START_TIME TIME,
	END_TIME TIME,
	ID VARCHAR(20)
)

---------------------------------------------------------------------
--CREATE TABLE STUDYROOM(
--	NUM VARCHAR PRIMARY KEY,	--좌석번호(1~128)
--	STATE TINYINT NOT NULL,		--자리의 상태 0(비어있음) / 1(남성) / 2(여성)
--	START_TIME TIME,		--시작시간
--	END_TIME TIME,			--종료시간(시작시간+4시간)
--	ID VARCHAR(20);				--좌석아이디
--)
--
--열람실
--A01~A62는 A열람실 / B01~B42는 B열람실 / C01~C24는 C열람실
---------------------------------------------------------------------

열람실 통계차트용 쿼리
SELECT
(SELECT COUNT(NUM) FROM STUDYROOM WHERE NUM LIKE 'a%') AS A전체,
(SELECT COUNT(NUM) FROM STUDYROOM WHERE NUM LIKE 'a%' AND STATE>0) AS A사용자,
(SELECT A전체-A사용자) AS A남은자리,
(SELECT COUNT(NUM) FROM STUDYROOM WHERE NUM LIKE 'b%') AS B전체,
(SELECT COUNT(NUM) FROM STUDYROOM WHERE NUM LIKE 'b%' AND STATE>0) AS B사용자,
(SELECT B전체-B사용자) AS B남은자리,
(SELECT COUNT(NUM) FROM STUDYROOM WHERE NUM LIKE 'c%') AS C전체,
(SELECT COUNT(NUM) FROM STUDYROOM WHERE NUM LIKE 'c%' AND STATE>0) AS C사용자,
(SELECT C전체-C사용자) AS C남은자리

스케줄링 테스트용 쿼리
UPDATE STUDYROOM SET START_TIME=ADDTIME(START_TIME, '05:00:00') WHERE NUM='a01'
UPDATE STUDYROOM SET END_TIME='01:00:00' WHERE NUM='a01'

SELECT * FROM STUDYROOM
DROP TABLE STUDYROOM

INSERT INTO STUDYROOM(NUM, STATE) VALUES('a01', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a02', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a03', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a04', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a05', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a06', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a07', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a08', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a09', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a10', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a11', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a12', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a13', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a14', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a15', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a16', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a17', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a18', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a19', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a20', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a21', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a22', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a23', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a24', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a25', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a26', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a27', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a28', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a29', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a30', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a31', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a32', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a33', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a34', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a35', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a36', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a37', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a38', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a39', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a40', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a41', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a42', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a43', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a44', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a45', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a46', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a47', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a48', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a49', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a50', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a51', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a52', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a53', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a54', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a55', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a56', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a57', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a58', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a59', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a60', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a61', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('a62', 0);

INSERT INTO STUDYROOM(NUM, STATE) VALUES('b01', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b02', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b03', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b04', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b05', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b06', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b07', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b08', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b09', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b10', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b11', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b12', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b13', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b14', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b15', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b16', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b17', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b18', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b19', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b20', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b21', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b22', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b23', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b24', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b25', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b26', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b27', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b28', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b29', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b30', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b31', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b32', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b33', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b34', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b35', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b36', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b37', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b38', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b39', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b40', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b41', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b42', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b43', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b44', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b45', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b46', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b47', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b48', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b49', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b50', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b51', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b52', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b53', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b54', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b55', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b56', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b57', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b58', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b59', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('b60', 0);


INSERT INTO STUDYROOM(NUM, STATE) VALUES('c01', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c02', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c03', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c04', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c05', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c06', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c07', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c08', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c09', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c10', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c11', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c12', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c13', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c14', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c15', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c16', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c17', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c18', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c19', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c20', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c21', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c22', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c23', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c24', 0);

INSERT INTO STUDYROOM(NUM, STATE) VALUES('c25', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c26', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c27', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c28', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c29', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c30', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c31', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c32', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c33', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c34', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c35', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c36', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c37', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c38', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c39', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c40', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c41', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c42', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c43', 0);
INSERT INTO STUDYROOM(NUM, STATE) VALUES('c44', 0);

